export interface IUserOne {
  id: number;
  person_name: string;
  mobile_number: string;
  company_name?: string;
  email_id?: string;
  country?: string;
  state?: string;
  district?: string;
  city?: string;
  area?: string;
  pincode?: string;
  address?: string;
  status?: number;
  created_at?: string;
  cntc_column_number_1: number | string;
  cntc_column_number_2: number | string;
  cntc_column_number_3: number | string;
  cntc_column_number_4: number | string;
  cntc_column_number_5: number | string;
  cntc_column_text_1: string;
  cntc_column_text_2: string;
  cntc_column_text_3: string;
  cntc_column_text_4: string;
  cntc_column_text_5: string;
  cntc_column_text_area_1: string;
  cntc_column_text_area_2: string;
  cntc_column_text_area_3: string;
  cntc_column_text_area_4: string;
  cntc_column_text_area_5: string;
  cntc_column_date_1: string;
  cntc_column_date_2: string;
  cntc_column_date_3: string;
  cntc_column_date_4: string;
  cntc_column_date_5: string;
  cntc_column_date_and_time_1: string;
  cntc_column_date_and_time_2: string;
  cntc_column_date_and_time_3: string;
  cntc_column_date_and_time_4: string;
  cntc_column_date_and_time_5: string;
  cntc_column_time_1: string;
  cntc_column_time_2: string;
  cntc_column_time_3: string;
  cntc_column_time_4: string;
  cntc_column_time_5: string;
  cntc_column_switch_1: number | boolean;
  cntc_column_switch_2: number | boolean;
  cntc_column_switch_3: number | boolean;
  cntc_column_switch_4: number | boolean;
  cntc_column_switch_5: number | boolean;
  cntc_column_decimal_1: number | string;
  cntc_column_decimal_2: number | string;
  cntc_column_decimal_3: number | string;
  cntc_column_decimal_4: number | string;
  cntc_column_decimal_5: number | string;
  cntc_column_dropdown_1: string;
  cntc_column_dropdown_2: string;
  cntc_column_dropdown_3: string;
  cntc_column_dropdown_4: string;
  cntc_column_dropdown_5: string;
  cntc_column_radio_1: string;
  cntc_column_radio_2: string;
  cntc_column_radio_3: string;
  cntc_column_radio_4: string;
  cntc_column_radio_5: string;
  column_number_1: number | string;
  column_number_2: number | string;
  column_number_3: number | string;
  column_number_4: number | string;
  column_number_5: number | string;
  column_text_1: string;
  column_text_2: string;
  column_text_3: string;
  column_text_4: string;
  column_text_5: string;
  column_text_area_1: string;
  column_text_area_2: string;
  column_text_area_3: string;
  column_text_area_4: string;
  column_text_area_5: string;
  column_date_1: string;
  column_date_2: string;
  column_date_3: string;
  column_date_4: string;
  column_date_5: string;
  column_date_and_time_1: string;
  column_date_and_time_2: string;
  column_date_and_time_3: string;
  column_date_and_time_4: string;
  column_date_and_time_5: string;
  column_time_1: string;
  column_time_2: string;
  column_time_3: string;
  column_time_4: string;
  column_time_5: string;
  column_switch_1: number | boolean;
  column_switch_2: number | boolean;
  column_switch_3: number | boolean;
  column_switch_4: number | boolean;
  column_switch_5: number | boolean;
  column_decimal_1: number | string;
  column_decimal_2: number | string;
  column_decimal_3: number | string;
  column_decimal_4: number | string;
  column_decimal_5: number | string;
  column_dropdown_1: string;
  column_dropdown_2: string;
  column_dropdown_3: string;
  column_dropdown_4: string;
  column_dropdown_5: string;
  column_radio_1: string;
  column_radio_2: string;
  column_radio_3: string;
  column_radio_4: string;
  column_radio_5: string;
}
